# Generated by Django 4.1.3 on 2024-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
