# Generated by Django 4.1.3 on 2024-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0002_sheetitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='subdivision_short_name',
            field=models.TextField(blank=True, null=True, verbose_name='Название подразделения (короткое)'),
        ),
    ]
