# Generated by Django 4.1.3 on 2024-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0003_subdivision_subdivision_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision_short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название подразделения (короткое)'),
        ),
    ]
