# Generated by Django 4.1.3 on 2024-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0005_alter_outgo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgo',
            old_name='decrease_count',
            new_name='count',
        ),
        migrations.AddField(
            model_name='outgo',
            name='is_decreased',
            field=models.BooleanField(default=False, verbose_name='Является расходом'),
        ),
    ]
