# Generated by Django 4.1.3 on 2024-01-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0006_rename_decrease_count_outgo_count_outgo_is_decreased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgo',
            name='is_decreased',
        ),
    ]
