# Generated by Django 4.1.3 on 2024-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0007_remove_outgo_is_decreased'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgo',
            name='sigh',
            field=models.IntegerField(default=1, verbose_name='+/-'),
        ),
    ]
