# Generated by Django 4.1.3 on 2024-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0008_outgo_sigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='sigh',
            field=models.IntegerField(default=1, verbose_name='+/-'),
        ),
    ]
