# Generated by Django 4.1.3 on 2024-01-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0010_rename_sigh_sheetitem_sign_remove_outgo_sigh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgodata',
            options={'ordering': ('-id',), 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AddField(
            model_name='sheetitem',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное поле'),
        ),
    ]
