# Generated by Django 4.1.3 on 2024-01-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outgo', '0011_alter_outgodata_options_sheetitem_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetitem',
            name='is_required',
        ),
    ]
